### ISSUE TITLE
CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered

### ISSUE THREAD

**Issue by chwshuang** [nagadit/DeepFaceLab_Linux#89]
error message:
F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_ECC_UNCORRECTABLE: uncorrectable ECC error encountered

my serser:
  Distributor ID: Ubuntu
  Description:    Ubuntu 20.04.6 LTS
  Release:        20.04
  linux Jupyter  
  GPU 4090 *

**Comment by chwshuang** [comment]
The problem was solved, and it was finally discovered that it was a hardware problem. I just changed the machine and redeployed Jupyter.
